source 'https://rubygems.org'

gem 'sinatra'
gem 'haml'
gem 'datamapper'
gem 'dm-paperclip'
gem 'fileutils'
gem 'stringex'
gem 'rmagick'
gem 'dm-sqlite-adapter'
gem 'activerecord'
gem 'sinatra-activerecord'
gem 'sqlite3'
gem 'dm-postgres-adapter'
